# Generated by Django 5.0.7 on 2024-07-25 12:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='photo',
            field=models.ImageField(default=None, upload_to='media/meals/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='student',
            name='photo',
            field=models.ImageField(upload_to='media/students/'),
        ),
    ]
