# Generated by Django 5.0.7 on 2024-07-25 12:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meal_photo_alter_student_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealentry',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
