# Generated by Django 5.0.7 on 2024-08-16 06:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_meal_photo_alter_student_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealentry',
            name='student_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.student', to_field='student_id'),
        ),
        migrations.AlterField(
            model_name='student',
            name='student_id',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
