# Generated by Django 5.0.7 on 2024-08-16 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_mealentry_student_id_alter_student_student_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mealentry',
            name='meal_type',
            field=models.CharField(choices=[('Breakfast', 'BREAKFAST'), ('Lunch', 'LUNCH'), ('Dinner', 'DINNER')], max_length=50),
        ),
        migrations.AlterField(
            model_name='menu',
            name='meal_time',
            field=models.CharField(choices=[('Breakfast', 'BREAKFAST'), ('Lunch', 'LUNCH'), ('Dinner', 'DINNER')], max_length=50),
        ),
    ]
